name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger jika ada push ke branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (atau bahasa lain yang digunakan)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ganti dengan versi yang digunakan dalam project

    - name: Install dependencies
      run: |
        npm install  # Jika menggunakan npm, ganti dengan perintah sesuai bahasa yang digunakan

    - name: Run unit tests
      run: |
        npm test  # Ganti dengan perintah testing yang digunakan dalam project

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Hanya dijalankan jika build dan test sukses

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Menambahkan SSH key ke GitHub secrets

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /path/to/your/app  # Ganti dengan path aplikasi di EC2
          git pull origin main
          npm install  # Atau perintah lain untuk mempersiapkan aplikasi
          pm2 restart app  # Restart aplikasi menggunakan pm2 (atau perintah yang sesuai)
        EOF
