name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger jika ada push ke branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ganti dengan versi Node.js yang kamu pakai

    - name: Install dependencies
      run: |
        npm install

    - name: Run unit tests
      run: |
        npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /var/www/html/front-end   # <-- Sesuaikan ke folder aplikasi kamu!
          git pull origin main
          npm install                  # Jika ini front-end static html, hapus baris ini
          pm2 restart all || pm2 start npm --name "your-app-name" -- start
        EOF
